aliases = [ ]
dependencies = [
	"Element",
	"Object.defineProperty"
]
license = "MIT"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/NonDocumentTypeChildNode/previousElementSibling"
spec = "https://dom.spec.whatwg.org/#dom-nondocumenttypechildnode-previouselementsibling"

[browsers]
# android = "all versions natively support this feature"
# bb = "Not on MDN"
chrome = "<4"
edge = "<12"
# edge_mob = "Not on MDN"
firefox = "<3.5"
# ios_chr = "Not on MDN"
# ios_saf = "all versions natively support this feature"
ie = "<9"
# ie_mob = "Not on MDN"
opera = "<10"
# op_mini = "Not on MDN"
op_mob = "<10.1"
safari = "<4"
firefox_mob = "<4"
# samsung_mob = "all versions natively support this feature"
