aliases = [
	"modernizr:urlparser",
	"blissfuljs",
	"default-3.4",
	"default-3.5",
	"default-3.6",
	"default",
	"URLSearchParams"
]
dependencies = [
	"Object.defineProperties",
	"Array.prototype.forEach",
	"Array.isArray",
	"Array.from",
	"Symbol.iterator"
]
notes = [ ]
license = "CC0-1.0"
repo = "https://github.com/inexorabletash/polyfill"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/URL"

[browsers]
chrome = "<61"
firefox = "<54"
edge = "<18.17134"
edge_mob = "<17"
ie = "9 - *"
ie_mob = "*"
safari = "<12"
firefox_mob = "<54"
opera = "<36"
op_mini = "*"
android = "<71"
samsung_mob = "<5"
bb = "*"
ios_saf = "<12"
