aliases = [ ]
dependencies = [
	"Event",
	"performance.now"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver"
spec = "http://rawgit.com/w3c/IntersectionObserver/master/index.html"
notes = [ ]
repo = "https://github.com/w3c/IntersectionObserver"

[browsers]
android = "<51"
bb = "*"
chrome = "< 51"
edge = "< 16"
edge_mob = "< 16"
firefox = "< 55"
firefox_mob = "< 55"
ie = "*"
ie_mob = "*"
ios_saf = "<16" # https://github.com/Financial-Times/polyfill-library/issues/1192#issuecomment-1180186718
op_mini = "*"
op_mob = "< 46"
opera = "< 45"
safari = "<16" # https://github.com/Financial-Times/polyfill-library/issues/1192#issuecomment-1180186718
samsung_mob = "< 7"
