dependencies = ["Intl", "Intl.~locale.en"]
license = "MIT"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts"
spec = "https://tc39.es/ecma402/#sec-Intl.DateTimeFormat.prototype.formatToParts"

[browsers]
chrome = "<71"
edge = "<18"
firefox = "<51"
firefox_mob = "<56"
ie = "*"
opera = "<58"
safari = "<11"
ios_saf = "<11"
android = "<7.1"
samsung_mob = "<7"