aliases = [
	"es5",
	"modernizr:es5object",
	"default-3.5",
	"default-3.6",
	"default",
	"blissfuljs"
]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.HasOwnProperty",
	"_ESAbstract.ToObject",
	"_ESAbstract.ToPropertyKey",
	"_ESAbstract.Type",
	"Function.prototype.bind"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor"

[browsers]
firefox = "<=35"
safari = "<=9"
ios_saf = "<=9"
firefox_mob = "<=35"
ie = "*"
android = "<=4.4"
edge = "<=13"
chrome = "<=44"
