dependencies = [
	"Object.assign",
	"Symbol",
	"Symbol.iterator",
	"Symbol.toStringTag"
]
license = "MIT"
repo = "https://github.com/medikoo/es6-iterator"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "*"
samsung_mob = "*"
