repo = "https://github.com/juggle/resize-observer/"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver"
spec = "https://drafts.csswg.org/resize-observer-1"
license = "Apache-2.0"
dependencies = [
  "Map",
  "MutationObserver",
  "requestAnimationFrame"
]

[browsers]
chrome = "<64"
edge = "*"
edge_mob = "*"
firefox = "<69"
ie = "*"
opera = "<51"
safari = "*"
android = "<5"
firefox_mob = "*"
samsung_mob = "<9"
ie_mob = "*"
op_mob = "<47"
ios_saf = "*"

[install]
module = "@juggle/resize-observer"
paths = [ "lib/exports/resize-observer.umd.js" ]

