repo = "https://github.com/que-etc/resize-observer-polyfill"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver"
spec = "https://drafts.csswg.org/resize-observer-1"
license = "MIT"

[browsers]
chrome = "<64"
edge = "*"
edge_mob = "*"
firefox = "<69"
ie = "*"
opera = "<51"
safari = "*"
android = "<67"
firefox_mob = "*"
samsung_mob = "<9"
ie_mob = "*"
op_mob = "<47"
ios_saf = "*"

[install]
module = "resize-observer-polyfill"
paths = [ "dist/ResizeObserver.js" ]

