aliases = [ "es2026" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.GetIterator",
	"_ESAbstract.IteratorClose",
	"_ESAbstract.IteratorStepValue",
	"_ESAbstract.RequireObjectCoercible",
	"_ESAbstract.ThrowCompletion",
	"Number.MAX_SAFE_INTEGER",
]

docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sumPrecise"
spec = "https://tc39.es/ecma262/#sec-math.sumprecise"

[browsers]
android = "*"
bb = "*"
chrome = "*"
firefox = "<137"
firefox_mob = "<137"
ie = "*"
ie_mob = "*"
opera = "*"
op_mob = "*"
op_mini = "*"
safari = "<26.2"
ios_saf = "<26.2"
samsung_mob = "*"

[install]
module = "math.sumprecise"
postinstall = "update.task.js"
clean = [ "polyfill.js" ]
