aliases = [ "caniuse:console-basic" ]
dependencies = [ "Window", "console" ]
spec = "https://console.spec.whatwg.org"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Console/timeStamp"

[browsers]
edge = "<12"
edge_mob = "<12"
ie = "<11"
firefox = "1 - 4"

