# add an alias for the original polyfill name which had a typo to maintain backwards compatibility
aliases = [ "HTMLCanvasElement.protoype.toBlob" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"ArrayBuffer",
	"atob",
	"Blob"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob"
license = "MIT"

[browsers]
chrome = "<50"
edge = "<79"
edge_mob = "*"
firefox = "<19"
safari = "<11"
ie = ">=10"
opera = "<37"
ios_saf = "<11"
