
version: 2.1
jobs:
  lint_js:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  unit_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run test-library
  publish_to_npm:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm publish
  polyfill_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Start test-server
          command: node ./test/polyfills/server.js
          background: true
      - run: node ./test/polyfills/remotetest.js targeted director browser=android
      - run: node ./test/polyfills/remotetest.js targeted director browser=chrome
      - run: node ./test/polyfills/remotetest.js targeted director browser=edge
      - run: node ./test/polyfills/remotetest.js targeted director browser=firefox
      - run: node ./test/polyfills/remotetest.js targeted director browser=ie
      - run: node ./test/polyfills/remotetest.js targeted director browser=ios
      - run: node ./test/polyfills/remotetest.js targeted director browser=safari
      - run:
          name: Testing polyfills
          command: node ./test/polyfills/remotetest.js targeted director
workflows:
  test:
    jobs:
      - lint_js:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              ignore: master
      - unit_tests:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              ignore: master
      - publish_to_npm:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - polyfill_tests:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              ignore: master
          requires:
            - lint_js
            - unit_tests
