aliases = [ "es6", "es2015" ]
dependencies = [ "Symbol" ]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/index.html#sec-symbol.split"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol"

[browsers]
android = "*"
bb = "10 - *"
chrome = "<50"
edge = "*"
edge_mob = "*"
firefox = "<45"
ie = "*"
ie_mob = "*"
opera = "<37"
safari = "<9.0"
ios_saf = "<10.0"
samsung_mob = "<5"
