aliases = [
	"scroll",
	"scrollBy",
	"scrollIntoView",
	"Element.prototype.scroll",
	"Element.prototype.scrollBy",
	"Element.prototype.scrollIntoView",
	"window.scroll",
	"window.scrollBy"
]
dependencies = [
	"requestAnimationFrame",
	"Function.prototype.bind",
	"getComputedStyle",
	"Object.defineProperty"
]
license = "MIT"
spec = "https://drafts.csswg.org/cssom-view/#smooth-scrolling"
repo = "https://github.com/magic-akari/seamless-scroll-polyfill"
docs = "https://developer.mozilla.org/en/docs/Web/CSS/scroll-behavior"

[browsers]
edge = "<79"
edge_mob = "*"
ie = "9 - *"
ie_mob = "9 - *"
firefox = "4 - 36"
opera = "*"
safari = "*"
chrome = "* - 60"
ios_saf = "*"
android = "*"

[install]
module = "seamless-scroll-polyfill"
postinstall = "update.task.js"
