#### Dependencies
dependencies = [
   "DOMRect"
]

#### Specification Link
spec = "https://drafts.fxtf.org/geometry/#dom-domrect-fromrect"

#### Documentation Link
docs = "https://developer.mozilla.org/en-US/docs/Web/API/DOMRect"

#### License
license = "MIT"

#### Browser compatibility
[browsers]
android = "<61"
chrome = "<61"
edge = "<79"
firefox = "<69"
firefox_mob = "<79"
ie = "9 - *"
ie_mob = "9 - *"
ios_chr = "<10.3"
ios_saf = "<10.3"
opera = "<48"
op_mob = "<45"
safari = "<10.1"
samsung_mob = "<8"
