aliases = [ "es6", "es2015", "modernizr:es6array" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.IsCallable",
]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.sort"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/sort"

[browsers]
edge = "<79"
edge_mob = "<79"
ie = "*"
ie_mob = "*"
firefox = "<3"
firefox_mob = "<3"
chrome = "<70"
safari = "<10.1"
android = "<70"
ios_saf = "<10.3"
opera = "<57"
samsung_mob = "<10"
