aliases = [ ]
dependencies = [ ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment"
spec = "https://dom.spec.whatwg.org/#interface-documentfragment"
notes = [ ]

[browsers]
android = "<4.4"
chrome = "<29"
edge = "<17"
firefox = "<24"
firefox_mob = "<24"
ie = "<=11"
ie_mob = "<=11"
ios_chr = "<8"
ios_saf = "<8"
op_mini = "<16"
opera = "<16"
safari = "<8"
samsung_mob = "<2"
