#### Aliases
aliases = []

#### Dependencies
dependencies = []

#### Specification Link
spec = "https://dom.spec.whatwg.org/#dom-element-getattributenames"

#### Documentation Link
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttributeNames"

#### License
license = "MIT"

#### Browser compatibility
[browsers]
android = "<61"
bb = "*"
chrome = "<61"
edge = "<18"
edge_mob = "<18"
firefox = "<45"
ios_chr = "<10.1"
ios_saf = "<10.1"
ie = "*"
ie_mob = "*"
opera = "<48"
op_mini = "<45"
safari = "<10.3"
firefox_mob = "<45"
samsung_mob = "<8"
