aliases = ["Intl"]
dependencies = [
    "Array.prototype.@@iterator",
    "Array.prototype.filter",
    "Array.prototype.indexOf",
    "Array.prototype.reduce",
    "Array.prototype.sort",
    "Function.prototype.bind",
    "Object.assign",
    "Object.defineProperty",
    "Object.keys"
]
license = "MIT"
spec = "https://tc39.es/ecma402/#sec-intl.getcanonicallocales"
repo = "https://github.com/formatjs/formatjs/tree/master/packages/intl-getcanonicallocales/"
docs = "https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl/getCanonicalLocales"

[browsers]
android = "*"
ie = "9 - *"
ie_mob = "9 - *"
edge = "<16"
edge_mob = "<16"
firefox = "<48"
opera = "*"
chrome = "<54"
safari = "<11"
ios_saf = "<11"
firefox_mob = "<56"
samsung_mob = "*"

[install]
module = "@formatjs/intl-getcanonicallocales"
paths = [ "polyfill.umd.js" ]
