aliases = [ "es6", "es2015" ]
dependencies = [ "Symbol" ]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/index.html#sec-symbol.unscopables"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol"

[browsers]
edge = "<13"
edge_mob = "<13"
ie = "*"
ie_mob = "*"
safari = "<9"
chrome = "<49.0.0"
firefox = "<45"
ios_saf = "< 9"
opera = "< 37"
samsung_mob = "<5"
android = "*"
bb = "10 - *"
