dependencies = [
  "Intl.DurationFormat",
  "Intl.ListFormat",
  "Intl.ListFormat.~locale.nmg",
  "Intl.Locale",
  "Intl.NumberFormat",
  "Intl.NumberFormat.~locale.nmg",
  "Intl.getCanonicalLocales",
  "Object.assign",
  "Object.keys",
  "Object.setPrototypeOf",
  "WeakMap"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DurationFormat"
license = "MIT"
notes = [
  "Locales must be specified separately by prefixing the locale name with `Intl.DurationFormat.~locale`, eg `Intl.DurationFormat.~locale.en-GB`."
]
repo = "https://github.com/formatjs/formatjs/tree/master/packages/intl-durationformat/polyfill.js"
spec = "https://tc39.es/proposal-intl-duration-format/#sec-intl-durationformat-constructor"

[browsers]
android = "*"
chrome = "<129"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "<115"
op_mob = "*"
safari = "<16.4"
ios_saf = "<16.4"
samsung_mob = "*"

[test]
ci = false
