aliases = [ "es2019" ]
dependencies = [ "_ESAbstract.CreateMethodProperty", "_ESAbstract.TrimString" ]
spec = "https://tc39.github.io/ecma262/#sec-string.prototype.trimstart"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart"

[browsers]
android = "<66"
bb = "*"
chrome = "<66"
edge = "*"
edge_mob = "*"
firefox = "<61"
firefox_mob = "<61"
ie = "*"
ie_mob = "*"
ios_chr = "<12.1"
ios_saf = "<12.1"
op_mini = "*"
op_mob = "*"
opera = "<53"
safari = "<12.1"
samsung_mob = "*"

