aliases = [ "es2025" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.EncodeForRegExpEscape",
	"_ESAbstract.StringToCodePoints",
]
spec = "https://tc39.es/proposal-regex-escaping/#sec-regexp.escape"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/escape"

[browsers]
android = "*"
chrome = "<136"
edge = "<136"
edge_mob = "<136"
firefox = "<134"
firefox_mob = "<134"
ie = "*"
ie_mob = "*"
opera = "<121"
op_mob = "<90"
safari = "<18.2"
ios_saf = "<18.2"
samsung_mob = "<29.0"
