aliases = [ "es2025" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.Type",
	"Object.prototype.toString",
	"Symbol",
	"Symbol.toStringTag",
]
spec = "https://tc39.es/proposal-is-error/#sec-error.iserror"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/isError"

[browsers]
android = "*"
bb = "*"
chrome = "<134"
edge = "*"
edge_mob = "*"
firefox = "<138"
firefox_mob = "<138"
ie = "*"
ie_mob = "*"
opera = "<120"
op_mob = "*"
op_mini = "*"
safari = "*"
ios_saf = "*"
samsung_mob = "*"
