aliases = [ "es6", "es2015", "default-3.6", "default" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.CreateIterResultObject",
	"_ESAbstract.GetMethod",
	"_ESAbstract.GetIterator",
	"_ESAbstract.IsCallable",
	"_ESAbstract.IteratorClose",
	"_ESAbstract.IteratorComplete",
	"_ESAbstract.IteratorNext",
	"_ESAbstract.IteratorStep",
	"_ESAbstract.IteratorValue",
	"_ESAbstract.OrdinaryCreateFromConstructor",
	"_ESAbstract.SameValueZero",
	"_ESAbstract.Type",
	"Symbol",
	"Symbol.iterator",
	"Symbol.species",
	"Object.isExtensible"
]
notes = [
	"The test suite for this polyfill is derived from work of Andrea Giammarchi which is [published under an MIT licence](https://github.com/WebReflection/es6-collections)"
]

docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map"

[browsers]
android = "<5.1"
bb = "10 - *"
chrome = "<49"
edge = "<13"
firefox = "<36"
firefox_mob = "<29"
ie = "*"
ie_mob = "*"
opera = "<25"
op_mob = "*"
op_mini = "*"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<5"
