{
  "name": "Test Polyfills Chrome",
  "on": {
    "pull_request": null,
    "workflow_dispatch": null
  },
  "concurrency": {
    "group": "browserstack",
    "cancel-in-progress": false
  },
  "jobs": {
    "test": {
      "strategy": {
        "max-parallel": 4,
        "fail-fast": false,
        "matrix": {
          "browser_version": [
            "9.0",
            "10.0",
            "11.0"
          ]
        }
      },
      "uses": "./.github/workflows/test-polyfills-base.yml",
      "secrets": "inherit",
      "with": {
        "browser": "chrome",
        "browser_version": "${{ matrix.browser_version }}",
      },
    }
  }
}
