{
  "name": "Test Polyfills Safari",
  "on": {
    "pull_request": null,
    "workflow_dispatch": null
  },
  "concurrency": {
    "group": "browserstack",
    "cancel-in-progress": false
  },
  "jobs": {
    "test": {
      "strategy": {
        "max-parallel": 4,
        "fail-fast": false,
        "matrix": {
          "browser_version": [
            "9.1",
            "10.1",
            "11.1",
            "12.1",
            "13.1",
            "14.1",
            "15.6",
            "16.5",
            "17.3"
          ]
        }
      },
      "uses": "./.github/workflows/test-polyfills-base.yml",
      "secrets": "inherit",
      "with": {
        "browser": "safari",
        "browser_version": "${{ matrix.browser_version }}"
      }
    }
  }
}