{
  "name": "Test Polyfills Edge",
  "on": {
    "pull_request": null,
    "workflow_dispatch": null
  },
  "concurrency": {
    "group": "browserstack-microsoft",
    "cancel-in-progress": false
  },
  "jobs": {
    "test": {
      "strategy": {
        "max-parallel": 1,
        "fail-fast": false,
        "matrix": {
          "browser_version": [
            "15.0",
            "16.0",
            "17.0",
            "18.0",
            "80.0",
            "121.0"
          ]
        }
      },
      "uses": "./.github/workflows/test-polyfills-base.yml",
      "secrets": "inherit",
      "with": {
        "browser": "edge",
        "browser_version": "${{ matrix.browser_version }}"
      }
    }
  }
}
