aliases = [ "es2026" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"Map",
]
license = "MIT"
spec = "https://tc39.es/ecma262/#sec-map.prototype.getorinsert"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/getOrInsert"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
firefox = "<144"
firefox_mob = "<144"
ie = "*"
ie_mob = "*"
opera = "*"
op_mob = "*"
op_mini = "*"
safari = "<26.2"
ios_saf = "<26.2"
samsung_mob = "*"
